name: Condarise
on: [push, pull_request]
jobs:
  set-conda-pkg-version:
    # Run for tags only
    if: "startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Fix meta YAML
        run: |
          MKFILE=hail/Makefile
          MAJOR_MINOR=$(grep -Po 'HAIL_MAJOR_MINOR_VERSION := \K.*(?=)' ${MKFILE})
          PATCH=$(grep -Po 'HAIL_PATCH_VERSION := \K.*(?=)' ${MKFILE})
          VERSION=${MAJOR_MINOR}.${PATCH}.dev${GITHUB_SHA:0:7}
          cat conda/hail/meta-template.yaml \
          | sed s/{version}/${VERSION}/ > conda/hail/meta.yaml

      - name: Upload meta YAML for build job
        uses: actions/upload-artifact@v2
        with:
          name: meta.yaml
          path: conda/hail/meta.yaml

  build-publish:
    # Run for tags only
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: set-conda-pkg-version
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - name: Download meta YAML
        uses: actions/download-artifact@v2
        with:
          name: meta.yaml
          path: conda/hail/

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: buildenv
          channels: cpg,conda-forge,bioconda,defaults
          channel-priority: true
          python-version: 3.7

      - name: Setup build env
        run: conda install pip conda-build anaconda-client

      - name: Build package
        run: conda build conda/hail

      - name: Upload to anaconda package repository
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
          upload ${CONDA_PREFIX}/conda-bld/**/*.tar.bz2
