name: Condarise
on:
  push:
    branches:
      - main
jobs:
  build-publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@main

      - name: Fix meta YAML
        run: |
          make -C hail python-version-info
          VERSION=$(cat hail/python/hail/hail_version)
          VERSION=${VERSION/-/.dev}
          cat conda/hail/meta-template.yaml \
          | sed s/{version}/${VERSION}/ > conda/hail/meta.yaml
          echo "$VERSION" >> version.txt

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: buildenv
          channels: cpg,conda-forge,bioconda,defaults
          channel-priority: true
          python-version: 3.7

      - name: Setup build env
        run: conda install pip conda-build anaconda-client

      - name: Build package
        run: conda build conda/hail

      - name: Upload to anaconda package repository
        run: |
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} \
          upload ${CONDA_PREFIX}/conda-bld/**/*.tar.bz2

      - name: Upload version tag
        uses: actions/upload-artifact@v2
        with:
          name: version.txt
          path: version.txt
  
  redeploy:
    runs-on: ubuntu-latest
    needs: build-publish
    steps:
      - uses: actions/checkout@main

      - name: Download version file
        uses: actions/download-artifact@v2
        with:
          name: version.txt
          path: /

      - name: Redeploy the analysis-server
        run: |
          curl --fail \
            -X POST \
            -H "Authorization: token ${{ secrets.ANALYSIS_SERVER_GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/populationgenomics/analysis-runner/actions/workflows/6364059/dispatches \
            -d "{\"ref\": \"main\", \"inputs\": {\"hail_version\": \"$(cat /version.txt)\"}}"
